server:
  port: 8763
 
eureka:
  instance:
    hostname: eurekaserver1
    appname: eureka-cluster
  environment: local
  client:
    serviceUrl:
      defaultZone: http://eurekaserver2:8764/eureka
    register-with-eureka: true
    fetch-registry: true
    
    
    