server:
  port: 8764

eureka:
  instance:
    hostname: eurekaserver2
    appname: eureka-cluster
  environment: local
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8763/eureka/


    register-with-eureka: true
    fetch-registry: true